### ISSUE TITLE
Trouble using this package from npm

### ISSUE THREAD

**Issue by OriginalEXE** [AKIRA-MIYAKE/contextual-element-identifier#3]
Hello,

First of all, thanks for maintaining this package, it is exactly what I need. That said, I am having trouble making use of it. I tried two ways, and both got me nowhere.

1.) In CodeSandbox, I tried to import the package, but it says it does not exist (even though it was successfully added as a dependency)

2.) Locally with webpack, the result is the same. I can successfully npm install the library, but the export I get is undefined:
```js
import cei from 'contextual-element-identifier';

console.log(cei); // returns undefined
```

I would appreciate any hints.

Thanks

**Comment by AKIRA-MIYAKE** [comment]
Sorry for the late response.
Maybe you've already solved it...

I wrote in README.md how to import the whole library.
https://github.com/AKIRA-MIYAKE/contextual-element-identifier#import

**Comment by OriginalEXE** [comment]
Thank you, I was able to get it to work :)
